export const otherLocalData = {
    announcement_of_changes_capital: null,
    announcement_of_changes_managers: null,
    announcing_account_number: null,
    assets_and_liabilities: null,
    auditor_representative: null,
    bank_account_turnover: null,
    claims_status: null,
    latest_insurance_staf: null,
    licenses: null,
    lock_announcement_of_changes_capital: false,
    lock_announcement_of_changes_managers: false,
    lock_announcing_account_number: false,
    lock_assets_and_liabilities: false,
    lock_auditor_representative: false,
    lock_bank_account_turnover: false,
    lock_claims_status: false,
    lock_latest_insurance_staf:false,
    lock_licenses: false,
    lock_product_catalog: false,
    lock_statutes: false,
    product_catalog: null,
    statutes: null,
  }